### PR TITLE
chore: add types

### PR DESCRIPTION
**Pull request by JiangWeixian**

### CODE REVIEW

**Comment by sapphi-red** [comment]
Thanks, but this is not required. TypeScript can infer the location from `exports` field.
https://arethetypeswrong.github.io/?p=artichokie%400.2.1

**Comment by JiangWeixian** [comment]
> Thanks, but this is not required. TypeScript can infer the location from `exports` field. https://arethetypeswrong.github.io/?p=artichokie%400.2.1

It looks only working with `"moduleResolution": "NodeNext"`.

**Comment by sapphi-red** [comment]
This package does not have `main` field and only have `exports` field. I think `"moduleResolution": "NodeNext"` or `"moduleResolution": "Bundler"` is required for this package.

**Comment by JiangWeixian** [comment]
get it

**Pull request closed without merging**
